<?php
namespace Tests\Zend\Validate;

class ValidateTest extends \Tests\TestCase
{
    /**
     * Ensure that the composer autoloader is finding the classes correctly.
     */
    public function testCanFindClasses()
    {
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_AdapterAbstract'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_AdapterInterface'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Code25'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Code25interleaved'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Code39'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Code39ext'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Code93'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Code93ext'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Ean2'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Ean5'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Ean8'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Ean12'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Ean13'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Ean14'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Ean18'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Gtin12'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Gtin13'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Gtin14'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Identcode'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Intelligentmail'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Issn'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Itf14'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Leitcode'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Planet'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Postnet'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Royalmail'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Sscc'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Upca'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode_Upce'));
        $this->assertTrue(class_exists('\Zend_Validate_Db_Abstract'));
        $this->assertTrue(class_exists('\Zend_Validate_Db_NoRecordExists'));
        $this->assertTrue(class_exists('\Zend_Validate_Db_RecordExists'));
        $this->assertTrue(class_exists('\Zend_Validate_File_Count'));
        $this->assertTrue(class_exists('\Zend_Validate_File_Crc32'));
        $this->assertTrue(class_exists('\Zend_Validate_File_ExcludeExtension'));
        $this->assertTrue(class_exists('\Zend_Validate_File_ExcludeMimeType'));
        $this->assertTrue(class_exists('\Zend_Validate_File_Exists'));
        $this->assertTrue(class_exists('\Zend_Validate_File_Extension'));
        $this->assertTrue(class_exists('\Zend_Validate_File_FilesSize'));
        $this->assertTrue(class_exists('\Zend_Validate_File_Hash'));
        $this->assertTrue(class_exists('\Zend_Validate_File_ImageSize'));
        $this->assertTrue(class_exists('\Zend_Validate_File_IsCompressed'));
        $this->assertTrue(class_exists('\Zend_Validate_File_IsImage'));
        $this->assertTrue(class_exists('\Zend_Validate_File_Md5'));
        $this->assertTrue(class_exists('\Zend_Validate_File_MimeType'));
        $this->assertTrue(class_exists('\Zend_Validate_File_NotExists'));
        $this->assertTrue(class_exists('\Zend_Validate_File_Sha1'));
        $this->assertTrue(class_exists('\Zend_Validate_File_Size'));
        $this->assertTrue(class_exists('\Zend_Validate_File_Upload'));
        $this->assertTrue(class_exists('\Zend_Validate_File_WordCount'));
        $this->assertTrue(class_exists('\Zend_Validate_Hostname_Biz'));
        $this->assertTrue(class_exists('\Zend_Validate_Hostname_Cn'));
        $this->assertTrue(class_exists('\Zend_Validate_Hostname_Com'));
        $this->assertTrue(class_exists('\Zend_Validate_Hostname_Jp'));
        $this->assertTrue(class_exists('\Zend_Validate_Ldap_Dn'));
        $this->assertTrue(class_exists('\Zend_Validate_Sitemap_Changefreq'));
        $this->assertTrue(class_exists('\Zend_Validate_Sitemap_Lastmod'));
        $this->assertTrue(class_exists('\Zend_Validate_Sitemap_Loc'));
        $this->assertTrue(class_exists('\Zend_Validate_Sitemap_Priority'));
        $this->assertTrue(class_exists('\Zend_Validate_Abstract'));
        $this->assertTrue(class_exists('\Zend_Validate_Alnum'));
        $this->assertTrue(class_exists('\Zend_Validate_Alpha'));
        $this->assertTrue(class_exists('\Zend_Validate_Barcode'));
        $this->assertTrue(class_exists('\Zend_Validate_Between'));
        $this->assertTrue(class_exists('\Zend_Validate_Callback'));
        $this->assertTrue(class_exists('\Zend_Validate_Ccnum'));
        $this->assertTrue(class_exists('\Zend_Validate_CreditCard'));
        $this->assertTrue(class_exists('\Zend_Validate_Date'));
        $this->assertTrue(class_exists('\Zend_Validate_Digits'));
        $this->assertTrue(class_exists('\Zend_Validate_EmailAddress'));
        $this->assertTrue(class_exists('\Zend_Validate_Exception'));
        $this->assertTrue(class_exists('\Zend_Validate_Float'));
        $this->assertTrue(class_exists('\Zend_Validate_GreaterThan'));
        $this->assertTrue(class_exists('\Zend_Validate_Hex'));
        $this->assertTrue(class_exists('\Zend_Validate_Hostname'));
        $this->assertTrue(class_exists('\Zend_Validate_Iban'));
        $this->assertTrue(class_exists('\Zend_Validate_Identical'));
        $this->assertTrue(class_exists('\Zend_Validate_InArray'));
        $this->assertTrue(class_exists('\Zend_Validate_Int'));
        $this->assertTrue(class_exists('\Zend_Validate_Interface'));
        $this->assertTrue(class_exists('\Zend_Validate_Ip'));
        $this->assertTrue(class_exists('\Zend_Validate_Isbn'));
        $this->assertTrue(class_exists('\Zend_Validate_LessThan'));
        $this->assertTrue(class_exists('\Zend_Validate_NotEmpty'));
        $this->assertTrue(class_exists('\Zend_Validate_PostCode'));
        $this->assertTrue(class_exists('\Zend_Validate_Regex'));
        $this->assertTrue(class_exists('\Zend_Validate_StringLength'));
        $this->assertTrue(class_exists('\Zend_Validate'));
    }
}